server:
  port: ${SERVER_PORT:8443}
spring:
  application:
    name: gateway
  profiles:
    active: core
  resources:
    cache:
      cachecontrol:
        no-cache: true
  cloud:
    nacos:
      config:
        enabled: true
        server-addr: 127.0.0.1:8848
        file-extension: yaml
        prefix: gateway
      discovery:
        enabled: true
        server-addr: 127.0.0.1:8848
    gateway:
      enabled: true
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true